### ISSUE TITLE
Implement propper Integration tests

### ISSUE THREAD

**Issue by ghost** [OneAgencySE/rust_at_one#1]
Right now we are missing proper testing where a full flow is involved. Start a DB, start the app and follow a flow.

**Comment by ghost** [comment]
https://actix.rs/docs/testing/

**Comment by Herlix** [comment]
A base setup of integration exists but it is somewhat cumbersome to use. Spinning up a docker or something similar to run the tests would be more sufficient. Plus, we need more tests and maybe some refactoring.
